### ISSUE TITLE
Is there update method to posted object?

### ISSUE THREAD

**Issue by kntmrkm** [arsduo/koala#464]
After `put_wall_post`, Is there update method to posted object ? By use a returned object id.

Perhaps this api in Original Graph API.
https://developers.facebook.com/docs/graph-api/reference/v2.3/post

**Comment by arsduo** [comment]
I'm not sure, to be honest. facebook.stackoverflow.com is probably the best place to ask about how to use the API — let me know that you find! And if it turns out that the gem can't handle the request, please open anotherissue and I'd be happy to update it. (Closing since this seems like more of an API question than an issue with the Koala Ruby gem — please reopen if I'm wrong.)
