### ISSUE TITLE
Wrap Faraday::Error::ConnectionFailed into Koala error

### ISSUE THREAD

**Issue by morgoth** [arsduo/koala#466]
It happens quite often that FB server is down (#345) which results in throwing `Faraday::Error::ConnectionFailed` in https://github.com/arsduo/koala/blob/7f3f478b656ca291df03056953f8f38cabfc17af/lib/koala/http_service.rb#L104

I think it makes sense to wrap it in Koala error i.e. `Koala::KoalaError::ConnectionFailed`.

I'll prepare a patch if you think this is a good idea.

**Comment by pratik60** [comment]
@morgoth What do you guys to get past this? Constant retry using sidekiq etc?

**Comment by morgoth** [comment]
@pratik60 Yes, I'm doing it in background job which is repeated in case of failure. I also described how I did it on https://cowbell-labs.com/2015-01-11-cleanup-bugtracker-from-frequently-erroring-background-jobs.html to not have such errors in bugtracker.

**Comment by arsduo** [comment]
Hi! Sorry about the late response. If you want to prepare a patch, I'd be happy to accept it. It's a good idea for the library to not expose what is essentially an implementation detail.

For compatibility with the existing code, what do you think of making the new error a subclass of Faraday::Error::ConnectionFailed? Then later, if Koala ever moved away from Faraday, we'd be able to change the underlying implementation without anyone else having to change their code.

**Comment by morgoth** [comment]
@arsduo Subclassing it from `Faraday::Error::ConnectionFailed` will mean that rescuing `Koala::Error` will not catch this exception, which I think will be very surprising.
What compatibility concern are you referring to?

**Comment by arsduo** [comment]
I'm concerned that raising a subclass of Koala::Error instead of propagating the Faraday error will break a lot of applications that currently check for the latter error — it's backwards-incompatible. I agree that it would be nice to encapsulate the problem, but since the functionality won't, effectively, change, I don't think it's necessary to do that.




Perhaps it'd make sense to make Koala::Error a module and include it in a bunch of other classes — that way you could catch the single error type, as you're suggesting, and Koala could have more appropriate error class types. (I haven't tested it in a while but I'm pretty sure you can rescue based on included modules.)




For now, if you want to do the smaller pull request based on the Faraday class, I think that'd still be worthwhile; if the larger change is more than you want to take on I'll include it in 3.0.




Thanks again!

**Comment by morgoth** [comment]
@arsduo It's implemented in #481

**Comment by arsduo** [comment]
Closing this per the discussion in #481.
