### ISSUE TITLE
update token without rebuilding Koala::Facebook::API

### ISSUE THREAD

**Issue by runa** [arsduo/koala#510]
Hi! I have a case where I need to change the token without rebuilding a `Koala::FB::API`:

On the Ads API there're some User limits but can be circumvented by using different users (this is recommended by FB staff, so...)

So, I'm currently doing a `graph.instance_eval{@access_token = new_token}`; would you accept a PR with the setter?

thanks

**Comment by arsduo** [comment]
You can provide a different access token for any individual request by passing it in the options hash (`api.get_connections("user", "connection", args_hash, access_token: token)`). Would that work?

Otherwise, I'll think about the setter. At first glance it seems odd to mutate the object in place -- to the extent you can share, what are the constraints on constructing a new one? (They're pretty cheap, after all.)

**Comment by arsduo** [comment]
Resolving since it's been a while. Let me know if it's still an issue.
