### ISSUE TITLE
Get connections vs Get Object

### ISSUE THREAD

**Issue by pratik60** [arsduo/koala#515]
Could someone quickly illustrate the difference between the two? 

I seem to be able to use both parallelly

**Comment by arsduo** [comment]
Because of how Facebook structures their API, you can basically use them the same way. (I'm kicking around the idea of merging them in a future version of Koala.) 

`get_object("me/friends")` is entirely identical to `get_connections("me", "friends")` -- it really just depends on which method signature makes more sense to you.

Thanks for using Koala! Let me know if I can help with anything else.
