### ISSUE TITLE
Post with privacy set to "SELF" does not work

### ISSUE THREAD

**Issue by nonato** [arsduo/koala#523]
Good evening,

I'm trying to post a hidden content (privacy = "SELF") in my main user account and my fanpage.

However, when I put on the fanpage, the content privacy is always "PUBLIC" and when I put on the user account, the content privacy is always "ALL_FRIENDS".

The code I am using for both cases is:

**facebook_graph = Koala :: Facebook :: API.new (token)**

**facebook_graph.put_connections ('me', 'feed', {message: 'I am testing!'}, {privacy: {value: 'SELF'}})**

OR

**facebook_graph.put_connections ('me', 'feed', {message: 'I am testing!' privacy: {value: 'SELF'}})**

Is something wrong?

Thank you very much in advance.

**Comment by arsduo** [comment]
Good question. Unfortunately this is more of an issue with the Facebook API than with Koala -- I don't actually know the answer. If you check on StackOverflow, hopefully someone will be able to help you there. (If it turns out that Koala doesn't support the request you need to make, let me know with technical details and we can get that fixed.) 

Good luck!
