### ISSUE TITLE
How to attach multiple photos to post?

### ISSUE THREAD

**Issue by tanraya** [arsduo/koala#524]
I need to attach multiple photos to post. Please help, i'm stuck on it.

**Comment by arsduo** [comment]
That's a good question; I don't actually know the answer to it. Since it's a question with the Facebook API rather than with Koala (which should support whatever attachment data you need to provide), can you try asking on StackOverflow? If it turns out Koala doesn't support whatever kind of request you need, if you can provide technical details I can help build the right code for it.

Good luck!
