### ISSUE TITLE
Uploading 360 Photo give error

### ISSUE THREAD

**Issue by harshamv** [arsduo/koala#536]
I am trying to upload a Spherical Image to Facebook from S3. by doing the following

```
begin
    @client.put_picture("https://s3.amazonaws.com/skreem-dev/PANO_20160717_120803_1.jpg", { allow_spherical_photo: true })  
rescue Exception => e  
    print e.inspect
end
```

It returns the following Error Message

```
#<Koala::Facebook::ServerError: type: OAuthException, code: 1, message: An unknown error has occurred. [HTTP 500]>
```

It works with any normal images from the same `s3 bucket`

*\* **UPDATE 1** **

Tried to upload the same image from `Godaddy` and i am facing the same issue.

*\* **UPDATE 2** **
Tried to upload via Graphy API Explorer, but getting the same error

```
{
  "error": {
    "message": "An unknown error has occurred.",
    "type": "OAuthException",
    "code": 1,
    "fbtrace_id": "CWqqwQ3WBq+"
  }
}
```

[![enter image description here](http://i.stack.imgur.com/JGYhH.jpg)](http://i.stack.imgur.com/JGYhH.jpg)

**Comment by harshamv** [comment]
Looks like Koala is timing out bcos of the size of the file!

**Comment by arsduo** [comment]
Hmm. Since you're seeing the same problem with the Graph Explorer, it looks like this is a bug on Facebook send. I would recommend opening an issue with them if you're still experiencing it (apologies for the late response!), or posting on facebook.stackoverflow.com.

I'm going to resolve this, but if you do discover that there's a problem with the gem itself, please either reopen or file a new issue and I'll be happy to help.
