### ISSUE TITLE
Rails 5 Deprecation issue (inject)

### ISSUE THREAD

**Issue by whitelancer** [arsduo/koala#546]
Hi there,
It looks like the Koala gem relies on injecting data into the params hash, which will be unavailable once Rails 5.1 is released due to the change in the way Parameters are built.

DEPRECATION WARNING: Method inject is deprecated and will be removed in Rails 5.1, as `ActionController::Parameters` no longer inherits from hash.
Using this deprecated behavior exposes potential security problems. If you continue to use this method you may be creating a security vulnerability in your app that can be exploited. Instead, consider using one of these documented methods which are not deprecated: http://api.rubyonrails.org/v5.0.0.1/classes/ActionController/Parameters.html (called from make_request at ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/koala-e12827c19a04/lib/koala/http_service.rb:81)

https://github.com/arsduo/koala/blob/v2.5.0rc1/lib/koala/http_service.rb#L81
https://github.com/arsduo/koala/blob/master/lib/koala/http_service.rb#L81

I think this would be quick fix by adding `.to_unsafe_h` before calling inject.  You might be able to do `.to_h` but that filters unsanitized vars so I'm not sure if that'll work for you.

Probably this would fix it, though I make no claims to it being the "right" solution.  According to the docs, you want to call permit and then .to_h.

`params = args.to_unsafe_h.inject({}) {|hash, kv| hash[kv.first.to_s] = kv.last.is_a?(UploadableIO) ? kv.last.to_upload_io : kv.last; hash}`

http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#actioncontroller-parameters-no-longer-inherits-from-hashwithindifferentaccess

`params.permit([:proceed_to, :return_to]).to_h`

**Comment by arsduo** [comment]
Great question! Koala doesn't hook into Rails itself, but I'm guessing that you're passing a set of parameters directly from the controller into the gem. Koala uses raw Ruby objects (it works both inside and outside Rails), so it doesn't have specific handle Rails data structures.

The best thing to do (which you've probably already done, apologies for the late response) is to permit the appropriate variables and then call `.to_h`. (Calling `.to_unsafe_h` doesn't seem ideal, since someone could in theory manipulate it, but a lot depends on your app.)

Since this isn't a Koala-specific issue I'm going to resolve this issue, but if you have any questions or find any bugs, feel free to reopen or open a new one!

**Comment by whitelancer** [comment]
Ah, that is interesting -- I can see how that would have caused this issue.  Thanks for investigating and responding.  We did basically fix this by ensuring we were passing a raw hash instead of the new Params, so that's definitely the issue.  Thank you!
