### ISSUE TITLE
url_for_oauth_code doesn't make faebook generate new token when adding permissions

### ISSUE THREAD

**Issue by pywebdesign** [arsduo/koala#561]
Let say our user have authenticated with our app with facebook and gave us the basic permissions

now when I generate them a new link to ask for more permission, facebook doesn't ask for it and simply return the same "code" which translate to the same access token without the added permission:

generate a link
```@facebook_permission_url = @oauth.url_for_oauth_code(permissions: "publish_actions")```

the user clicked the link and got redirect here. We generate an access token from the code in the redirect url
```@token = @oauth.get_access_token(params[:code])```

the ```@token``` still doesn't have the publish permissions

is this normal behaviour? what is the flow to request new permissions?

thank you

**Comment by arsduo** [comment]
Hi! I'm honestly not sure what the expected Facebook behavior is at this point. The best place to ask is http://facebook.stackoverflow.com — if you turn on Koala's debug mode to show the calls that are being made and post on there, you'll hopefully get an answer. 

I'm closing this because it seems like a Facebook issue. If it turns out to be an issue with Koala, please reopen this issue and we'll take care of it!
