### ISSUE TITLE
test users' locale defaults to de_DE

### ISSUE THREAD

**Issue by AlexWellsHS** [arsduo/koala#588]
Hello!

I am using the Koala gem to create test users for UI Automation testing. Every test user I create through Koala has their locale set to "de_DE", which makes it quite the hassle to touch a button in the UI that can only be queried for in a certain language.

Is it possible to create a test user with a specified default locale? Or is it possible to create a test user, and use user_graph_api or oath to change their locale?

Any info would be very helpful. Thanks!

edit: I am running tests in the Xamarin device farm, and when the test users are created on their servers, they default to "de_DE". Is there any way to override this? Most likely a question for Xamarin, but any help would be greatly appreciated.

**Comment by arsduo** [comment]
That's a very strange situation. I have no idea, unfortunately, I've never
looked into that. Do the Facebook docs have anything about setting locale?

I would actually suggest that you post on facebook.stackoverflow.com,
that's the best place for API questions. As a sole maintainer,
unfortunately don't have the resources dig into individual questions about
how Facebook works :/

Since this doesn't appear to be a bug with the Ruby code itself, I'm going
to close this issue. If it does turn out that the gem needs to be changed
(or you find any other issues) please reopen this or open a new issue.

Thanks for using Koala!

**Comment by arsduo** [comment]
As a side note, I've released a beta version of Koala 3.0! There shouldn't
be any significant differences for most users (all internal changes). If
you have a little bit of time to test it out I would love any feedback!
