### ISSUE TITLE
Getting a NoMethodError: undefined method `oauth_token' for User

### ISSUE THREAD

**Issue by OmarZV** [arsduo/koala#597]
Apologies for the beginner question. I'm trying to use the Koala gem on my app. Currently, I have devise and omniauth (for facebook login). And they work great - I'm able to register users easily. What I want to do now though is utilize Koala to get access to Facebook data from my logged in Users. However, I'm getting an error "NoMethodError: undefined method oauth_token for #<User:0x007fc4681ad770>"

User.rb
`class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
     :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name     
      user.avatar = URI.parse(auth.info.image)
      user.oauth_token = auth.credentials.token #Added this after learning about Koala
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(self.oauth_token)
  end
end`

![screen shot 2017-03-07 at 4 24 03 am](https://cloud.githubusercontent.com/assets/16312270/23649850/f81250e4-02ed-11e7-8e9c-97b84a60ef52.png)

**Comment by arsduo** [comment]
Hmm, interesting. What is the schema.rb entry for the users table? What
columns are on it?

Are you able to access oauth_token in other parts of the app? If you add
byebug to your gemfile and throw in a debugger at that point, what do you
see?

This looks like an issue in your Rails app more than an issue with Koala,
so StackOverflow might be a better place to ask, but hopefully those
questions will point you in the right direction.

On Mar 7, 2017 03:24, "Omar Khedr" <notifications@github.com> wrote:

Apologies for the beginner question. I'm trying to use the Koala gem on my
app. Currently, I have devise and omniauth (for facebook login). And they
work great - I'm able to register users easily. What I want to do now
though is utilize Koala to get access to Facebook data from my logged in
Users. However, I'm getting an error "NoMethodError: undefined method
`oauth_token' for #User:0x007fc4681ad770"

User.rb
`class User < ApplicationRecord
devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :trackable, :validatable, :omniauthable,
omniauth_providers: [:facebook]

def self.from_omniauth(auth)
where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
user.email = auth.info.email
user.password = Devise.friendly_token[0,20]
user.username = auth.info.name
user.avatar = URI.parse(auth.info.image)
user.oauth_token = auth.credentials.token #Added this after learning about
Koala
end
end

def facebook
@facebook <https://github.com/facebook> ||= Koala::Facebook::API.new(self.
oauth_token)
end
end`

[image: screen shot 2017-03-07 at 4 24 03 am]
<https://cloud.githubusercontent.com/assets/16312270/23649850/f81250e4-02ed-11e7-8e9c-97b84a60ef52.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arsduo/koala/issues/597>, or mute the thread

**Comment by OmarZV** [comment]
Thank you so much for responding mate!! Your comment was super helpful. I think its in the schema where the problem is --> I listed it below. I've put in Stack overflow but got little traction, any help would be amazing champ :1st_place_medal:  :smile: 

**schema.rb**
`create_table "users", force: :cascade do |t|
  t.string   "email",                  default: "", null: false
  t.string   "encrypted_password",     default: "", null: false
  t.string   "reset_password_token"
  t.datetime "reset_password_sent_at"
  t.datetime "remember_created_at"
  t.integer  "sign_in_count",          default: 0,  null: false
  t.datetime "current_sign_in_at"
  t.datetime "last_sign_in_at"
  t.string   "current_sign_in_ip"
  t.string   "last_sign_in_ip"
  t.datetime "created_at",                          null: false
  t.datetime "updated_at",                          null: false
  t.string   "avatar_file_name"
  t.string   "avatar_content_type"
  t.integer  "avatar_file_size"
  t.datetime "avatar_updated_at"
  t.string   "username"
  t.string   "provider"
  t.string   "uid"
  t.index ["email"], name: "index_users_on_email", unique: true
  t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
end`

**Comment by arsduo** [comment]
Hmm. It looks like there's no `oauth_token` column on the users table, which fits with the error message. You'll need to add that column and figure out how to get Devise to record it when a use logs in (which it might do automatically). After that the code you have in the model to instantiate a Koala API object should work.

**Comment by OmarZV** [comment]
Thank you so much champ!! I think that solved it!!

**Comment by arsduo** [comment]
Awesome! Glad to be able to help :)
