### ISSUE TITLE
Upload multiple photos simultaneously

### ISSUE THREAD

**Issue by rusikf** [arsduo/koala#599]
Hello, is it possible to upload multiple photos simultaneously?
I am using `put_picture` method for uploading for any of my facebook pages, but I can't upload multiple photos at once.
[It looks](https://developers.facebook.com/docs/graph-api/photo-uploads), that there is no way to upload multiple photos to pages, is it true ?

With best regards, Ruslan.

**Comment by arsduo** [comment]
You can't send multiple pictures in a single put_picture request, but you
can send multiple requests at once using the Batch API. Would that work?

On Mar 9, 2017 10:25, "Ruslan Korolev" <notifications@github.com> wrote:

Hello, is it possible to upload multiple photos simultaneously?
I am using put_picture method for uploading for any of my facebook pages,
but I can't upload multiple photos at once.
It looks <https://developers.facebook.com/docs/graph-api/photo-uploads>,
that there is no way to upload multiple photos to pages, is it true ?

With best regards, Ruslan.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arsduo/koala/issues/599>, or mute the thread

**Comment by rusikf** [comment]
May be , but I want to create one post with multiple photos, not many posts, is it possible?

**Comment by arsduo** [comment]
Oh, I see. I don't know the answer to that. I'd suggest asking on
facebook.stackoverflow.com if you can't find any info on there already.
That's the best place to ask Facebook API-related questions; the Github
repo is more focused on issues with the Ruby code.

If you're about to find an answer but Koala doesn't support how to do that,
please reopen the issue or open a new one. (If you figure it out either
way, let me know! I'm curious.)

**Comment by raysango** [comment]
@rusikf @arsduo if the issue is to create one post with multiple images then you can do that Koala, what you need to do is first upload pictures with published: false and you will get photo id for each upload, after that build the attachments hash to be posted to the feed 
@images = [image_1, image_2, image_3]
images_hash = {}
@image_ids = []
@images.each do |file|
   fb_photo = page_graph.put_picture(file, 'image/jpeg', published: false)
   @image_ids << fb_photo["id"]
end
@image_ids.each_with_index{|id, index| images_hash["attached_media[#{index}]"] = "{media_fbid: #{id}}"}

@page_graph.put_connections('me', 'feed', images_hash, 'message' => 'post text')

**Comment by puneet18190** [comment]
@raysango 

My requirement is to post multiple pictures with title, description and link.
I tried your code mentioned above, it posts multiple pictures but not add title, description and link under post.

Code:

@images = [image1, image2, image3, image4]
images_hash = {}
@image_ids = []
@images.each do |file|
  fb_photo = @api.put_picture(file, 'image/jpeg', published: false)
  @image_ids << fb_photo["id"]
end
@image_ids.each_with_index{|id, index| images_hash["attached_media[#{index}]"] = "{media_fbid: #{id}}"}

@api.put_connections('me', 'feed', images_hash, 
  'message' => "my message",
  'link' => "https://www.test.com",
  'name' => "name",
  'description' => "description")


However if I tried below code then I got title, description, link in a post but one picture is add under post.
@api.put_connections('me', 'feed', 
  'message' => "my message",
  'link' => "https://www.test.com",
  'name' => "name",
  'description' => "description",
  'picture' => 'image_link')

I need to know how to add title, description, link with multiple pictures in a post on Facebook?

**Comment by raysango** [comment]
@puneet18190 I think you need to change the order of the parameters passed try this:

@page_graph.put_connections('me', 'feed', images_hash.merge({'message' => 'post text'}))

I just tested it and it is posting multiple pictures with message as post text, regarding link and description What happens if you include them in the message parameter?

**Comment by puneet18190** [comment]
@raysango 

Thanks for your help.

**Comment by puneet18190** [comment]
@raysango 

Can you please let me know how to get a Facebook token which is never expired.
I get a token from https://developers.facebook.com/tools/explorer/ but it expired after some time.

**Comment by puneet18190** [comment]
@raysango 

I tried to add html tags in message like:

@page_graph.put_connections('me', 'feed', images_hash.merge({'message' => " <a href='www.test.com'>Testing</a>"}))

It display text with tags on page, not add html. How to add html tags in message?

**Comment by raysango** [comment]
@puneet18190 you can use html_safe on a string with html tags, didn't test it but should work, regarding the FB token I'm sure there a lot of the same question on Stack Overflow and it's kinda different subject from this issue
