### ISSUE TITLE
Unable to post visitor post to a facebook page using graph API.

### ISSUE THREAD

**Issue by GauthamSakthiveeran-zz** [arsduo/koala#644]
I am trying to post a visitor post to a facebook page using graph API(Using Koala Gem). Getting the below error,

Koala::Facebook::ClientError: type: OAuthException, code: 200, message: (#200) Requires either publish_to_groups permission and app being installed in the group, or manage_pages and publish_pages as an admin with sufficient administrative permission, x-fb-trace-id: DlkUWs8nor8 [HTTP 403] from /Users/sengottaiann/.rvm/gems/ruby-2.4.1@twitter_fix/gems/koala-3.0.0/lib/koala/api.rb:50:in `graph_call'

Can someone help me with this ?

**Comment by slucha** [comment]
I am having the same error trying to post to my own page. It seems to be due to the new Facebook api changes where this is not possible anymore.
https://stackoverflow.com/questions/52405905/unable-to-post-visitor-post-to-a-facebook-page-using-graph-api (last comment on initial post)
Any workaround possible here?

**Comment by ylecuyer** [comment]
This error was not directly related to koala, you can refer to the Facebook graph API reference when this happens: https://developers.facebook.com/docs/graph-api/reference
